/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#00667e",
        primary: "#005bbf",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#adc7ff",
        error: "#ba1a1a",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeeef",
        "on-primary": "#ffffff",
        "secondary-fixed": "#e4dfff",
        "on-secondary-fixed-variant": "#4029ba",
        outline: "#727785",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c1c6d6",
        surface: "#f8f9fa",
        "on-surface": "#191c1d",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004e60",
        "tertiary-fixed-dim": "#47d6ff",
        "on-tertiary-container": "#ffffff",
        "on-secondary-fixed": "#160066",
        "primary-container": "#1a73e8",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#001a41",
        "secondary-container": "#6f5fea",
        "secondary-fixed-dim": "#c6bfff",
        "surface-container-high": "#e7e8e9",
        "on-background": "#191c1d",
        "on-primary-container": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#adc7ff",
        background: "#f8f9fa",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed-variant": "#004493",
        "on-surface-variant": "#414754",
        "surface-container-low": "#f3f4f5",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#005bc0",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "tertiary-container": "#00819e",
        "surface-dim": "#d9dadb",
        "tertiary-fixed": "#b6ebff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#001f28",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d8e2ff",
        secondary: "#5644d0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "display-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "headline-lg-mobile": ["Public Sans"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
